add Users and ChatRooms
Evenstein/Chat-Project pull request #1
Opened 2018-12-16 14:04 UTC by Evenstein

2018-12-18 02:37 UTC, stahor requested changes

2018-12-18 02:37 UTC, stahor commented on app/controllers/chat_rooms_controller.rb
> +    @chat_rooms = ChatRoom.all
Вот такие вот штуки опасны тем, что комнат может быть, скажем, миллион. И прилага просто повесится попытавшись их все загрузить. Решается обычно пагинацией.

2018-12-18 02:37 UTC, stahor commented on app/helpers/chat_rooms_helper.rb
> +module ChatRoomsHelper
пустые хелперы обычно не создают

2018-12-18 02:37 UTC, stahor commented on app/models/user.rb
> +  has_many :messages, dependent: :destroy
т.е. если удалить юзера, пропадут и все его сообщения?

2018-12-18 02:37 UTC, stahor commented on app/models/user.rb
> +    email.split('@')[0]
`first`
вруби рубокопа в рубимайне. Там есть поддержка в настройках

2018-12-18 02:37 UTC, stahor commented on app/views/chat_rooms/_chat_room.slim
> +  = link_to "Enter #{chat_room.title}", chat_room_path(chat_room)
вставляй пустые строки в конце файла. Настрой редактор, чтобы сам вставлял.

2018-12-18 02:37 UTC, stahor commented on config/database.yml
> +  username: root
тебе по-хорошему пароль для локальной базы не нужен. Почитай про peer authentication

2018-12-18 02:37 UTC, stahor commented on test/controllers/chat_rooms_controller_test.rb
> +  test "should get index" do
в компании все пишут на rspec

2019-01-19 06:44 UTC, Evenstein commented on app/controllers/chat_rooms_controller.rb
> +    @chat_rooms = ChatRoom.all
fixed by using kaminari

2019-01-19 06:45 UTC, Evenstein commented on app/helpers/chat_rooms_helper.rb
> +module ChatRoomsHelper
deleted

2019-01-19 06:50 UTC, Evenstein commented on app/models/user.rb
> +  has_many :messages, dependent: :destroy
Таки да. Ок, уберу пока. Хотя это и сомнительно. Viber, например, не парится по поводу сохранения месаг юзера

2019-01-19 07:10 UTC, Evenstein commented on app/models/user.rb
> +    email.split('@')[0]
turned on

2019-01-19 07:16 UTC, Evenstein commented on app/views/chat_rooms/_chat_room.slim
> +  = link_to "Enter #{chat_room.title}", chat_room_path(chat_room)
Настройку включил, но пока особо не вижу чтобы вставлялись. Посмотрим что будет дальше

2019-01-26 05:24 UTC, merged